<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.foogaro</groupId>
    <artifactId>jpa-employer</artifactId>
    <version>1.0.0</version>
    <name>jpa-employer</name>
    <description>A JPA demo for the Java library write-behind-streaming.</description>

    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>21</java.version>
        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.test.source>21</maven.test.source>
        <maven.test.target>21</maven.test.target>
        <maven.deploy.skip>true</maven.deploy.skip>
        <mysql.version>8.0.30</mysql.version>
        <lombok.version>1.18.34</lombok.version>
        <redis-om.version>1.0.0-RC2</redis-om.version>
        <jedis.version>5.1.0</jedis.version>
        <jackson-databind.version>2.17.2</jackson-databind.version>
        <gson.version>2.10.1</gson.version>
        <write-behind-streaming.version>0.2.1</write-behind-streaming.version>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.4</version>
        <relativePath/>
    </parent>

    <dependencies>
        <dependency>
            <groupId>io.github.foogaro</groupId>
            <artifactId>write-behind-streaming</artifactId>
            <version>${write-behind-streaming.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>${mysql.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>com.redis.om</groupId>
            <artifactId>redis-om-spring</artifactId>
            <version>${redis-om.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson-databind.version}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>com.google.code.gson</groupId>-->
<!--            <artifactId>gson</artifactId>-->
<!--            <version>${gson.version}</version>-->
<!--        </dependency>-->
    </dependencies>

    <repositories>
        <repository>
            <id>sonatype-snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </repository>
        <repository>
            <id>maven-central</id>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>
        <repository>
            <id>ossrh</id>
            <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.github.foogaro</groupId>
                            <artifactId>write-behind-streaming</artifactId>
                            <version>${write-behind-streaming.version}</version>
                        </path>
                    </annotationProcessorPaths>
<!--                    <annotationProcessorPaths>-->
<!--                        <annotationProcessor>com.foogaro.redis.wbs.core.annotation.CachingPatternsAnnotationProcessorssor</annotationProcessor>-->
<!--                    </annotationProcessorPaths>-->
                    <showWarnings>true</showWarnings>
                    <compilerArgs>
                        <arg>-Xlint:processing</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <name>${project.artifactId}</name>
                    </image>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
